import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { marked } from 'marked';
export const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const xml=escape;
const date=value=>value instanceof Date?value.toISOString().slice(0,10):String(value||'');
export function readContent(drafts=false){
 const site=matter(fs.readFileSync('content/site.md','utf8')).data;
 const read=dir=>fs.readdirSync(dir).filter(f=>f.endsWith('.md')&&!f.startsWith('_')).map(f=>{const p=matter(fs.readFileSync(path.join(dir,f),'utf8'));return {...p.data,body:p.content,updated:date(p.data.updated),date:date(p.data.date)};});
 const pages=read('content/pages');
 const all=read('content/blog').map(p=>({...p,article:true,slug:'/blog/'+p.slug+'/'}));
 const slugs=new Set();
 for(const p of [...pages,...all]){
  if(!/^\/(?:[a-z0-9-]+\/)*$/.test(p.slug)||slugs.has(p.slug))throw Error('Invalid or duplicate slug: '+p.slug);
  slugs.add(p.slug);
  if(!p.title||!p.description||!/^\d{4}-\d{2}-\d{2}$/.test(p.updated)||Number.isNaN(Date.parse(p.updated)))throw Error('Missing or invalid metadata: '+p.slug);
  if(p.article&&typeof p.published!=='boolean')throw Error('Article needs boolean published: '+p.slug);
  if(p.article&&p.published&&(!/^\d{4}-\d{2}-\d{2}$/.test(p.date)||Number.isNaN(Date.parse(p.date))||p.date>new Date().toISOString().slice(0,10)))throw Error('Published article needs a real publication date: '+p.slug);
 }
 return {site,pages,posts:all.filter(p=>drafts||p.published).sort((a,b)=>b.date.localeCompare(a.date)||a.slug.localeCompare(b.slug))};
}
const arrow='<span aria-hidden="true">↗</span>';
const link=(label,href,cls='')=>`<a class="${cls}" href="${escape(href)}">${escape(label)} ${arrow}</a>`;
function picture(site){return `<figure class="portrait"><picture><source type="image/avif" srcset="/images/portrait-480.avif 480w, /images/portrait-800.avif 800w, /images/portrait-1086.avif 1086w" sizes="(max-width: 800px) calc(100vw - 48px), 440px"><source type="image/webp" srcset="/images/portrait-480.webp 480w, /images/portrait-800.webp 800w, /images/portrait-1086.webp 1086w" sizes="(max-width: 800px) calc(100vw - 48px), 440px"><img src="/images/portrait-800.webp" alt="${escape(site.portraitAlt)}" width="1086" height="1448" fetchpriority="high"></picture><figcaption>${escape(site.portraitCaption)}</figcaption></figure>`;}
function cards(posts,site){return posts.map(p=>`<article class="post-card"><p class="eyebrow">${escape(p.published?p.date:site.draftLabel)}</p><h2><a href="${p.slug}">${escape(p.title)}</a></h2><p>${escape(p.description)}</p>${link(site.readArticle,p.slug,'text-link')}</article>`).join('');}
export function renderPage(page,data,assets={js:'/src/main.js'},preview=false){
 const s=data.site,e=escape,home=page.slug==='/',about=page.slug==='/about/',blog=page.slug==='/blog/';
 const noindex=preview||page.notFound||page.article&&!page.published;
 const href=s.url+page.slug;
 const person={'@type':'Person','@id':s.url+'/#person',name:s.fullName,url:s.url,email:s.email,telephone:s.phone,image:s.url+'/images/portrait-800.webp',sameAs:s.socials.map(v=>v.href)};
 const graph=[person,{'@type':'WebSite','@id':s.url+'/#website',url:s.url,name:s.name,inLanguage:'en',author:{'@id':person['@id']}},{'@type':page.article&&page.published?'BlogPosting':about?'ProfilePage':'WebPage','@id':href+'#page',url:href,name:page.title,headline:page.title,description:page.description,inLanguage:'en',dateModified:page.updated+'T00:00:00Z',author:{'@id':person['@id']},...(about?{mainEntity:{'@id':person['@id']}}:{}),...(page.article&&page.published?{datePublished:page.date+'T00:00:00Z',image:s.url+'/images/share.png'}:{})}];
 const structured=JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c');
 const header=`<header class="site-header container"><a class="brand" href="/">${e(s.name)}<span class="brand-dot" aria-hidden="true">.</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="navigation" aria-label="${e(s.menuOpen)}" data-open="${e(s.menuOpen)}" data-close="${e(s.menuClose)}"><span></span><span></span></button><nav id="navigation" aria-label="${e(s.navLabel)}">${s.nav.map(n=>`<a href="${n.href}"${page.slug===n.href?' aria-current="page"':''}>${e(n.label)}</a>`).join('')}${link(s.connect,'#contact','nav-contact')}</nav></header>`;
 const footer=`<footer id="contact" class="contact"><div class="container"><p class="eyebrow">${e(s.connect)}</p><div class="contact-grid"><div><h2>${e(s.contactHeading)}</h2><p>${e(s.contactLead)}</p></div><div class="contact-links">${link(s.email,'mailto:'+s.email)}${link(s.phone,'tel:'+s.phoneLink)}</div></div><div class="footer-bottom"><p>${e(s.footerNote)}</p><div>${s.socials.map(n=>link(n.label,n.href)).join('')}${link(s.rssLabel,'/feed.xml')}</div></div></div></footer>`;
 let body='';
 if(home){
  const sections=marked.lexer(page.body);let blocks=[],current=null;
  for(const token of sections){if(token.type==='heading'&&token.depth===2){current={title:token.text,tokens:[]};blocks.push(current);}else if(current)current.tokens.push(token);}
  body=`<section class="home-hero"><div class="hero-copy"><p class="eyebrow"><span class="status-dot" aria-hidden="true"></span>${e(page.eyebrow)}</p><h1>${e(page.heading)}</h1><p class="lead">${e(page.lead)}</p><div class="hero-actions">${link(page.primaryLabel,page.primaryHref,'button')}${link(page.secondaryLabel,page.secondaryHref,'text-link')}</div></div>${picture(s)}</section><section class="perspectives">${blocks.map((b,i)=>`<article><p class="number" aria-hidden="true">0${i+1}</p><h2>${e(b.title)}</h2><div>${marked.parser(b.tokens)}</div></article>`).join('')}</section><section class="writing-intro"><div><p class="eyebrow">${e(s.nav[1].label)}</p><h2>${e(s.writingHeading)}</h2></div><div><p>${e(s.writingLead)}</p>${link(s.writingLink,'/blog/','text-link')}</div></section>${data.posts.length?`<div class="post-grid">${cards(data.posts.slice(0,3),s)}</div>`:''}`;
 }else if(blog){body=`<section class="page-hero"><p class="eyebrow">${e(page.eyebrow)}</p><h1>${e(page.heading)}</h1><p class="lead">${e(page.lead)}</p></section>${data.posts.length?`<section class="post-grid">${cards(data.posts,s)}</section>`:`<section class="empty-writing"><span class="asterisk" aria-hidden="true">✳</span><div><h2>${e(s.emptyHeading)}</h2><p>${e(s.emptyLead)}</p>${link(s.linkedinLabel,s.socials.find(n=>n.label==='LinkedIn').href,'text-link')}</div></section>`}`;
 }else if(page.notFound){body=`<section class="page-hero"><p class="eyebrow">404</p><h1>${e(s.notFoundTitle)}</h1><p class="lead">${e(s.notFoundLead)}</p>${link(s.backHome,'/','button')}</section>`;
 }else if(page.article){body=`<article class="article"><header class="article-hero">${link(s.backToWriting,'/blog/','text-link')}<p class="eyebrow">${e(page.published?s.publishedLabel+' '+page.date:s.draftLabel)}</p><h1>${e(page.title)}</h1><p class="lead">${e(page.description)}</p><p class="article-meta">${e(s.fullName)} · ${e(s.updatedLabel)} ${e(page.updated)}</p></header><div class="prose">${marked.parse(page.body)}</div></article>`;
 }else{body=`<section class="about-hero"><div><p class="eyebrow">${e(page.eyebrow)}</p><h1>${e(page.heading)}</h1><p class="lead">${e(page.lead)}</p></div>${picture(s)}</section><article class="prose about-prose">${marked.parse(page.body)}</article>`;}
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(page.title)}</title><meta name="description" content="${e(page.description)}">${noindex?'<meta name="robots" content="noindex, nofollow">':''}<link rel="canonical" href="${e(href)}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="alternate" type="application/rss+xml" title="${e(s.name)} — ${e(s.nav[1].label)}" href="/feed.xml"><meta property="og:type" content="${page.article?'article':'website'}"><meta property="og:title" content="${e(page.title)}"><meta property="og:description" content="${e(page.description)}"><meta property="og:url" content="${e(href)}"><meta property="og:image" content="${s.url}/images/share.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${e(s.fullName)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${e(page.title)}"><meta name="twitter:description" content="${e(page.description)}"><meta name="twitter:image" content="${s.url}/images/share.png">${(assets.css||[]).map(css=>`<link rel="stylesheet" href="${css}">`).join('')}<script type="application/ld+json">${structured}</script></head><body class="${home?'home':page.article?'article-page':'inner-page'}"><a class="skip-link" href="#main">${e(s.skip)}</a>${header}<main id="main" class="container">${body}</main>${footer}<script type="module" src="${assets.js}"></script></body></html>`;
}
export function notFound(data,assets,preview=false){return renderPage({slug:'/404/',title:data.site.notFoundTitle+' — '+data.site.name,description:data.site.notFoundLead,updated:'2026-10-02',notFound:true},data,assets,preview);}
export function sitemap(data){return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...data.pages,...data.posts.filter(p=>p.published)].map(p=>`<url><loc>${xml(data.site.url+p.slug)}</loc><lastmod>${p.updated}</lastmod></url>`).join('')}</urlset>`;}
export function rss(data){return `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${xml(data.site.name)} — ${xml(data.site.nav[1].label)}</title><link>${data.site.url}/blog/</link><description>${xml(data.site.writingLead)}</description><language>en</language>${data.posts.filter(p=>p.published).map(p=>`<item><title>${xml(p.title)}</title><link>${data.site.url+p.slug}</link><guid>${data.site.url+p.slug}</guid><description>${xml(p.description)}</description><pubDate>${new Date(p.date+'T00:00:00Z').toUTCString()}</pubDate></item>`).join('')}</channel></rss>`;}
